### ISSUE TITLE
What does this symbol mean?

### ISSUE THREAD

**Issue by Jannisus04** [IceMoonMagic/Satisfactory-Splitter-Calculator#4]
Hi I got a Problem. Sometimes I get this symbol and I dont know what it means. Its like the splitter symbol but with a square in it.
![Unbenannt](https://user-images.githubusercontent.com/121231937/209123760-6b28300a-58c1-4116-801f-6393e7b2f503.PNG)

And then i get like not splittable numbers:
![Unbenadnnt](https://user-images.githubusercontent.com/121231937/209123875-70d9618a-ae2b-40b0-9d15-40c04b8929ed.PNG)
I mean how should I split this. Hope you can help me.

**Comment by IceMoonMagic** [comment]
That would be the symbol for a splitter, the idea being to use it to max out (setting to any) one or two belts (in this case, a MK 1 / 60 IPM belt) and overflow the last one (in this case, the remaining 78 items).

I should also note that smart splitters store three items before they start to overflow, so if the input drops for some reason, the "standard" flow end up with those extras. They also make it harder to increase output with the same ratio by simply increasing input, but they can also vastly simplify the results by getting a better ratio for the rest of the system.

If you would like to disable this behavior, you can use the `-b 0` argument on the command line or set `MK` to `0` in the config YAML / JSON, depending on how you run the program.
