### ISSUE TITLE
Stuck?

### ISSUE THREAD

**Issue by emphzd** [IceMoonMagic/Satisfactory-Splitter-Calculator#5]
Hey! Thanks for this wonderfull tool

Recently, it seems to be stuck in the default configuration and won't bulge from the 60 out and 30, 15, 15 in. Changing the split ratio numbers in any way sends it back to this default configuration. Am I doing something wrong?

Thank you!

**Comment by IceMoonMagic** [comment]
Strange... what's weirder is that the Split Evenly tab, which uses the same component, seems to work correctly.

I'll see what I can find.

**Comment by IceMoonMagic** [comment]
Fixed with commit 2b2f963 and pages redeployed.

Had some logic I thought was need be unneeded and be what caused this issue.
